AWSTemplateFormatVersion: "2010-09-09"

Description: Root stack that deploys VPC, ALB, and ASG as nested stacks.

Resources:
  VCPStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://backupbucket0001.s3.us-east-1.amazonaws.com/vpc-subnets.yaml
  
  NatGatewayStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://backupbucket0001.s3.us-east-1.amazonaws.com/natgateway.yaml
      Parameters:
        VpcID: !GetAtt VCPStack.Outputs.VpcID
        PublicSubnet1: !GetAtt VCPStack.Outputs.PublicSubnet1
        PublicSubnet2: !GetAtt VCPStack.Outputs.PublicSubnet2
        PrivateSubnet1: !GetAtt VCPStack.Outputs.PrivateSubnet1
        PrivateSubnet2: !GetAtt VCPStack.Outputs.PrivateSubnet2

  ALBStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://backupbucket0001.s3.us-east-1.amazonaws.com/alb.yaml
      Parameters:
        VpcID: !GetAtt VCPStack.Outputs.VpcID
        PublicSubnet1: !GetAtt VCPStack.Outputs.PublicSubnet1
        PublicSubnet2: !GetAtt VCPStack.Outputs.PublicSubnet2
        SecurityGroupALB: !GetAtt VCPStack.Outputs.SecurityGroupALB
  
  ASGStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://backupbucket0001.s3.us-east-1.amazonaws.com/asg.yaml
      Parameters:
        VpcID: !GetAtt VCPStack.Outputs.VpcID
        PrivateSubnet1: !GetAtt VCPStack.Outputs.PrivateSubnet1
        PrivateSubnet2: !GetAtt VCPStack.Outputs.PrivateSubnet2
        SecurityGroupWeb: !GetAtt VCPStack.Outputs.SecurityGroupWeb
        ALBTargetGroup: !GetAtt ALBStack.Outputs.ALBTargetGroup
